apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-shared-vectordb-secret
data:
  {{- if .Values.vectorDB.useExternal }}
  ###################################
  # external vector db
  ###################################
  {{- if eq .Values.vectorDB.externalType "weaviate"}}
  WEAVIATE_API_KEY: {{ .Values.vectorDB.externalWeaviate.apiKey | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "qdrant" }}
  QDRANT_API_KEY: {{ .Values.vectorDB.externalQdrant.apiKey | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "milvus" }}
  MILVUS_TOKEN: {{ .Values.vectorDB.externalMilvus.token | b64enc | quote }}
  MILVUS_PASSWORD: {{ .Values.vectorDB.externalMilvus.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "relyt" }}
  RELYT_PASSWORD: {{ .Values.vectorDB.externalRelyt.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "pgvecto-rs" }}
  PGVECTO_RS_PASSWORD: {{ .Values.vectorDB.externalPgVectoRS.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "pgvector" }}
  PGVECTOR_PASSWORD: {{ .Values.vectorDB.externalPgvector.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "tencent" }}
  TENCENT_VECTOR_DB_API_KEY: {{ .Values.vectorDB.externalTencentVectorDB.apiKey | b64enc | quote }}
  TENCENT_VECTOR_DB_PASSWORD: {{ .Values.vectorDB.externalTencentVectorDB.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "opensearch" }}
  OPENSEARCH_PASSWORD: {{ .Values.vectorDB.externalOpenSearch.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "elasticsearch" }}
  ELASTICSEARCH_PASSWORD: {{ .Values.vectorDB.externalElasticsearch.password | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "analyticdb" }}
  ANALYTICDB_PASSWORD: {{ .Values.vectorDB.externalAnalyticDB.password | b64enc | quote }}
  ANALYTICDB_NAMESPACE_PASSWORD: {{ .Values.vectorDB.externalAnalyticDB.namespacePassword | b64enc | quote }}
  {{- else if eq .Values.vectorDB.externalType "lindorm" }}
  LINDORM_PASSWORD: {{ .Values.vectorDB.externalLindorm.password | b64enc | quote }}
  {{- end }}
  {{- else }}
  ###################################
  # internal vector db
  ###################################
  {{- if .Values.weaviate.enabled }}
    {{- if .Values.weaviate.authentication.apikey.enabled }}
  # The Weaviate API key.
  WEAVIATE_API_KEY: {{ first .Values.weaviate.authentication.apikey.allowed_keys | b64enc | quote }}
    {{- end }}
  {{- else if .Values.qdrant.enabled }}
  QDRANT_API_KEY: {{ .Values.qdrant.apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}