{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-api-secret
data:
  SECRET_KEY: {{ .Values.global.appSecretKey | b64enc | quote }}
  CODE_EXECUTION_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- if .Values.api.innerApi.enabled }}
  INNER_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.enterprise.enabled }}
  ENTERPRISE_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  ENTERPRISE_PLUGIN_MANAGER_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.enterprise.enabled .Values.global.otel.enabled }}
  ENTERPRISE_OTLP_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  {{- include "dify.otel.secret" . | nindent 2 }}
  GITHUB_CLIENT_ID: {{ .Values.api.oauth.github.clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.api.oauth.github.clientSecret | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.api.oauth.google.clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.api.oauth.google.clientSecret | b64enc | quote }}
  {{- if eq .Values.global.integrations.notion.integrationType "internal" }}
  NOTION_INTERNAL_SECRET: {{ .Values.global.integrations.notion.internalSecret | b64enc | quote }}
  {{- else }}
  NOTION_CLIENT_ID: {{ .Values.global.integrations.notion.clientId | b64enc | quote }}
  NOTION_CLIENT_SECRET: {{ .Values.global.integrations.notion.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}