{{- if or .Values.api.enabled .Values.worker.enabled .Values.workerBeat.enabled (include "dify.hasEnabledAdditionalWorkers" .) }}
{{- $difyDb := include "dify.difyDatasource" . | fromJson }}
{{- $difyDbPass := include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "dify") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-shared-db-secret
data:
  DB_PASSWORD: {{ (($difyDbPass | default $difyDb.password) | b64enc) | quote }}
{{- end }}