apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-shared-celery-secret
data:
  # Use redis as the broker, and redis db 1 for celery broker.
  {{- if .Values.externalRedis.enabled }}
    {{- if .Values.externalRedis.useSSL }}
      {{- with .Values.externalRedis }}
      {{- $password := .password | urlquery | replace "+" "%20" }}
      {{- $username := .username | urlquery | replace "+" "%20" }}
  CELERY_BROKER_URL: {{ printf "rediss://%s:%s@%s:%v/1" .username $password .host .port | b64enc | quote }}
      {{- end }}
    {{- else }}
      {{- with .Values.externalRedis }}
      {{- $password := .password | urlquery | replace "+" "%20" }}
      {{- $username := .username | urlquery | replace "+" "%20" }}
  CELERY_BROKER_URL: {{ printf "redis://%s:%s@%s:%v/1" .username $password .host .port | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- else if .Values.redis.enabled }}
  {{- $redisHost := printf "%s-redis-master" .Release.Name }}
  {{- $password := .Values.redis.global.redis.password | urlquery | replace "+" "%20" }}
  {{- $username := .Values.redis.global.redis.username | urlquery | replace "+" "%20" }}
  CELERY_BROKER_URL: {{ printf "redis://:%s@%s:%v/1" $password $redisHost .Values.redis.master.service.ports.redis | b64enc | quote }}
  {{- end }}