{{- if .Values.enterpriseRbac.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.fullname" . }}-enterprise-rbac-svc
  labels:
{{ include "dify.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rbac
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
{{ include "dify.selectorLabels" . | indent 4 }}
    app: {{ template "dify.fullname" . }}-enterprise-rbac
{{- end }}
