{{- if and .Values.weaviate.enabled .Values.weaviate.authentication.apikey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-secret
data:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: {{ first .Values.weaviate.authentication.apikey.allowed_keys | b64enc | quote }}
{{- end }}