{{- if .Values.workerBeat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-worker-beat-secret
data:
  SECRET_KEY: {{ .Values.global.appSecretKey | b64enc | quote }}
  {{- include "dify.otel.secret" . | nindent 2 }}
{{- end }}