{{- $dbInstance := include "dify.dbInstance" . | fromJson }}

{{- if .Values.enterprise.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-enterprise-secret
data:
  PASSWORD_ENCRYPTION_KEY: {{ .Values.enterprise.passwordEncryptionKey | b64enc | quote }}
  DIFY_SECRET_KEY: {{ .Values.global.appSecretKey | b64enc | quote }}
  DASHBOARD_JWT_SECRET_KEY: {{ .Values.enterprise.appSecretKey | b64enc | quote }}
  ENTERPRISE_SECRET_KEY_SALT: {{ .Values.enterprise.adminAPIsSecretKeySalt | b64enc | quote }}
  DIFY_INNER_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- if .Values.enterprise.innerApi.enabled }}
  ENTERPRISE_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  DIFY_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "dify")) | default $dbInstance.password) | b64enc | quote }}
  ENTERPRISE_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "enterprise")) | default $dbInstance.password) | b64enc | quote }}
{{- end }}
