{{- $dbInstance := include "dify.dbInstance" . | fromJson }}

{{- if .Values.enterpriseRbac.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-enterprise-rbac-secret
data:
  ENTERPRISE_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "enterprise")) | default $dbInstance.password) | b64enc | quote }}
  DASHBOARD_JWT_SECRET_KEY: {{ .Values.enterprise.appSecretKey | b64enc | quote }}
  ENTERPRISE_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
{{- end }}
