{{- if .Values.sandbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-sandbox-secret
data:
  API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
{{- end }}