apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-shared-mail-secret
data:
  {{- if eq .Values.mail.type "resend" }}
  RESEND_API_KEY: {{ .Values.mail.resend.apiKey | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.mail.type "smtp" }}
  SMTP_PASSWORD: {{ .Values.mail.smtp.password | b64enc | quote }}
  {{- end }}