{{- if .Values.ssrfProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.fullname" . }}-ssrf-proxy-svc
  labels:
{{ include "dify.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: ssrf-proxy
      port: 3128
      protocol: TCP
      targetPort: 3128
  selector:
{{ include "dify.selectorLabels" . | indent 4 }}
    app: {{ template "dify.fullname" . }}-ssrf-proxy
{{- end }}