{{- if and .Values.api.enabled .Values.collaboration.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.fullname" . }}-api-websocket-svc
  labels:
{{ include "dify.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
{{ include "dify.selectorLabels" . | indent 4 }}
    app: {{ template "dify.fullname" . }}-api-websocket
{{- end }}
