{{- if or .Values.worker.enabled (include "dify.hasEnabledAdditionalWorkers" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-worker-secret
data:
  SECRET_KEY: {{ .Values.global.appSecretKey | b64enc | quote }}
  CODE_EXECUTION_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- if .Values.enterprise.enabled }}
  ENTERPRISE_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  ENTERPRISE_PLUGIN_MANAGER_API_SECRET_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.enterprise.enabled .Values.global.otel.enabled }}
  ENTERPRISE_OTLP_API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
  {{- end }}
  {{- include "dify.otel.secret" . | nindent 2 }}
  {{- if eq .Values.global.integrations.notion.integrationType "internal" }}
  NOTION_INTERNAL_SECRET: {{ .Values.global.integrations.notion.internalSecret | b64enc | quote }}
  {{- else }}
  NOTION_CLIENT_ID: {{ .Values.global.integrations.notion.clientId | b64enc | quote }}
  NOTION_CLIENT_SECRET: {{ .Values.global.integrations.notion.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
