{{- $dbInstance := include "dify.dbInstance" . | fromJson }}

{{- if .Values.enterpriseAudit.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-enterprise-audit-secret
data:
  DASHBOARD_JWT_SECRET_KEY: {{ .Values.enterprise.appSecretKey | b64enc | quote }}
  DIFY_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "dify")) | default $dbInstance.password) | b64enc | quote }}
  ENTERPRISE_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "enterprise")) | default $dbInstance.password) | b64enc | quote }}
  AUDIT_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "audit")) | default $dbInstance.password) | b64enc | quote }}

  # OSS
  {{- if and (eq .Values.persistence.type "s3") (not .Values.persistence.s3.useAwsManagedIam) }}
  AWS_ACCESS_KEY: {{ .Values.persistence.s3.accessKey | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.persistence.s3.secretKey | b64enc | quote }}
  {{- end }}
  TENCENT_COS_SECRET_ID: {{ .Values.persistence.tencentCos.secretId | b64enc | quote }}
  TENCENT_COS_SECRET_KEY: {{ .Values.persistence.tencentCos.secretKey | b64enc | quote }}
  AZURE_BLOB_STORAGE_CONNECTION_STRING: {{- $suffix := .Values.persistence.azureBlob.endpointSuffix }} {{ if $suffix }}{{ printf "DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=%s;EndpointSuffix=%s" .Values.persistence.azureBlob.accountName .Values.persistence.azureBlob.accountKey $suffix | b64enc | quote }}{{ else }}{{ printf "DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=%s" .Values.persistence.azureBlob.accountName .Values.persistence.azureBlob.accountKey | b64enc | quote }}{{ end }}

  ALIYUN_OSS_ACCESS_KEY_ID: {{ .Values.persistence.aliyunOss.accessKey | b64enc | quote }}
  ALIYUN_OSS_ACCESS_KEY_SECRET: {{ .Values.persistence.aliyunOss.secretKey | b64enc | quote }}
  VOLCENGINE_TOS_ACCESS_KEY: {{ .Values.persistence.volcengineTos.accessKey | b64enc | quote }}
  VOLCENGINE_TOS_SECRET_KEY: {{ .Values.persistence.volcengineTos.secretKey | b64enc | quote }}
  GCS_CREDENTIALS: {{ .Values.persistence.googleStorage.serviceAccountJson | b64enc | quote }}
  HUAWEI_OBS_ACCESS_KEY: {{ .Values.persistence.huaweiObs.accessKey | b64enc | quote }}
  HUAWEI_OBS_SECRET_KEY: {{ .Values.persistence.huaweiObs.secretKey | b64enc | quote }}
{{- end }}
