apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-shared-redis-secret
data:
{{- if .Values.externalRedis.enabled }}
  {{- include "dify.redis.assertNoCluster" . }}
  {{- with .Values.externalRedis }}
  REDIS_PASSWORD: {{ .password | toString | b64enc | quote }}
    {{- if .sentinel.enabled }}
  REDIS_SENTINEL_PASSWORD: {{ .sentinel.password | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- else if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.global.redis.password | toString | b64enc | quote }}
{{- end }}
