{{- $dbInstance := include "dify.dbInstance" . | fromJson }}
{{- if .Values.enterpriseCollector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.fullname" . }}-enterprise-collector-secret
data:
  SECRET_KEY: {{ .Values.global.appSecretKey | b64enc | quote }}
  ENTERPRISE_DB_PASS: {{ ((include "dify.dbCredentialPassword" (dict "Values" .Values "credentialKey" "enterprise")) | default $dbInstance.password) | b64enc | quote }}
  API_KEY: {{ .Values.global.innerApiKey | b64enc | quote }}
{{- end }}
